name: All Tests

on:
  push:
    branches: [ "main" ]

jobs:
  tests:
    runs-on: macos-13
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v3

      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '14.3.1'

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
      
      - name: Setup
        run: ./Scripts/ci_setup.sh

      - name: Mocks Generation
        run: ./Scripts/mock_gen.sh ./Modules

      - name: Run Tests
        run: |
            xcodebuild test \
            -project '[SBER] ExchangeRates.xcodeproj' \
            -scheme '[SBER] ExchangeRates' \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.4' \
            -skipPackagePluginValidation \
            CODE_SIGNING_REQUIRED=NO
